public class GUIPanel extends javax.swing.JPanel {

    /**
     * Creates new form GUIPanel
     */
    public GUIPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBotton = new javax.swing.JButton();

        JBotton.setText("Start undersøgelse");
        JBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(JBotton)
                .addContainerGap(583, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(JBotton)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBottonActionPerformed
        // TODO add your handling code here:
       if(JBotton.getText().equals("Påbegynd undersøgelse")){
           System.out.println("Påbegynd undersøgelse");
           JBotton.setText("Stop undersøgelse");
       }else{
           System.out.println("Stopper");
           JBotton.setText("Stop undersøgelse");
           
       }
    }//GEN-LAST:event_JBottonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBotton;
    // End of variables declaration//GEN-END:variables
}
